CREATE DATABASE [BD_ALFA]
ON  PRIMARY 
(
	NAME = N'BD_ALFA', 
	FILENAME = N'E:\SQLServerDB\BD_ALFA.mdf' , 
	SIZE = 8192KB , 
	FILEGROWTH = 65536KB 
)
LOG ON 
( 
	NAME = N'BD_ALFA_log', 
	FILENAME = N'E:\SQLServerDB\BD_ALFA_log.ldf' , 
	SIZE = 8192KB , 
	FILEGROWTH = 65536KB 
)
GO


