USE master;
GO

CREATE DATABASE TURISMO
ON PRIMARY
( 
	NAME='TURISMO',
	FILENAME= 'E:\SQLServerDB\TURISMO.mdf',
	SIZE=4MB,
	MAXSIZE=10MB,
	FILEGROWTH=1MB
),
FILEGROUP TURISMO_FG1
( 
	NAME = 'TURISMO_FG1_Data1',
	FILENAME = 'E:\SQLServerDB\TURISMO_FG1_Data1.ndf',
	SIZE = 1MB,
	MAXSIZE=10MB,
	FILEGROWTH=1MB
),
( 
	NAME = 'TURISMO_FG1_Data2',
	FILENAME = 'E:\SQLServerDB\TURISMO_FG1_Data2.ndf',
	SIZE = 1MB,
	MAXSIZE=10MB,
	FILEGROWTH=1MB
)
LOG ON
( 
	NAME='TURISMOLOG',
	FILENAME = 'E:\SQLServerDB\TURISMOLOG.ldf',
	SIZE=1MB,
	MAXSIZE=10MB,
	FILEGROWTH=1MB
);
GO