USE [master]
GO
ALTER DATABASE [TURISMO] ADD FILEGROUP [TURISMO_FG2]
GO
ALTER DATABASE [TURISMO] ADD FILE ( NAME = N'TURISMO_FG2_Data1', FILENAME = N'e:\SQLServerDB\TURISMO_FG2_Data1.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB ) TO FILEGROUP [TURISMO_FG2]
GO
