BACKUP DATABASE [EUREKABANK] 
TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\EUREKABANK.bak' 
WITH NOFORMAT, NOINIT,  NAME = N'EUREKABANK-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [EUREKABANK] 
TO  DISK = N'D:\BACKUP\EUREKABANK_001.bak' 
GO