
-- MODO DE RECUPERACION DE LA BASE DE DATOS

USE [master]
GO

ALTER DATABASE [BD_ALFA] SET RECOVERY SIMPLE;
GO

ALTER DATABASE [BD_ALFA] SET RECOVERY BULK_LOGGED;
GO

ALTER DATABASE [BD_ALFA] SET RECOVERY FULL;
GO
