--CREACION DE USUARIOS Y ASIGNACION DE ROLES--

USE [master]
GO
CREATE LOGIN [xserna] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [afuller] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [jleverling] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [mpeacock] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [sbuchanan] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [msuyama] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [rking] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [adodsworth] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [lcallahan] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [uperez] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [gsmith] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [pvannels] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO
CREATE LOGIN [pmartinez] WITH PASSWORD=N'admin', DEFAULT_DATABASE=[Northwind]
GO

USE [Northwind]
GO
CREATE USER [xserna] FOR LOGIN [xserna]
GO
CREATE USER [afuller] FOR LOGIN [afuller]
GO
CREATE USER [jleverling] FOR LOGIN [jleverling]
GO
CREATE USER [mpeacock] FOR LOGIN [mpeacock]
GO
CREATE USER [sbuchanan] FOR LOGIN [sbuchanan]
GO
CREATE USER [msuyama] FOR LOGIN [msuyama]
GO
CREATE USER [rking] FOR LOGIN [rking]
GO
CREATE USER [adodsworth] FOR LOGIN [adodsworth]
GO
CREATE USER [lcallahan] FOR LOGIN [lcallahan]
GO
CREATE USER [uperez] FOR LOGIN [uperez]
GO
CREATE USER [gsmith] FOR LOGIN [gsmith]
GO
CREATE USER [pvannels] FOR LOGIN [pvannels]
GO
CREATE USER [pmartinez] FOR LOGIN [pmartinez]
GO

USE [Northwind]
GO
ALTER ROLE [ROL_ADMINISTRADOR] ADD MEMBER [xserna]
GO
ALTER ROLE [ROL_VICEPRESIDENTE] ADD MEMBER [afuller]
GO
ALTER ROLE [ROL_VENDEDOR_CORPORATIVO] ADD MEMBER [jleverling]
GO
ALTER ROLE [ROL_VENDEDOR_CORPORATIVO] ADD MEMBER [mpeacock]
GO
ALTER ROLE [ROL_GERENTE_DE_VENTAS] ADD MEMBER [sbuchanan]
GO
ALTER ROLE [ROL_VENDEDOR_LOCAL] ADD MEMBER [msuyama]
GO
ALTER ROLE [ROL_VENDEDOR_LOCAL] ADD MEMBER [rking]
GO
ALTER ROLE [ROL_VENDEDOR_LOCAL] ADD MEMBER [adodsworth]
GO
ALTER ROLE [ROL_ADMINISTRADOR_INTERNO] ADD MEMBER [lcallahan]
GO
ALTER ROLE [ROL_VENDEDOR_DE_TIENDA] ADD MEMBER [uperez]
GO
ALTER ROLE [ROL_VENDEDOR_DE_TIENDA] ADD MEMBER [gsmith]
GO
ALTER ROLE [ROL_VENDEDOR_DE_TIENDA] ADD MEMBER [pvannels]
GO
ALTER ROLE [ROL_VENDEDOR_DE_TIENDA] ADD MEMBER [pmartinez]
GO